

package telas;


import conexao.Conexao;
import get.GetSetProfessor;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

  public class Cadastro_Professor extends javax.swing.JFrame{      
   // conecta con = new conecta();
    
    
     public Cadastro_Professor() {
        initComponents();
     //   con.conexao();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
     Connection con = new Conexao().getConnection();
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1_voltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1_nome = new javax.swing.JLabel();
        txtLoginProf = new javax.swing.JTextField();
        jLabel2_senha = new javax.swing.JLabel();
        jLabel2_senha1 = new javax.swing.JLabel();
        passSenhaProf = new javax.swing.JPasswordField();
        jButton2_cadastrar = new javax.swing.JButton();
        jLabel2_senha2 = new javax.swing.JLabel();
        cmbArea = new javax.swing.JComboBox<>();
        txtNomeProf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "AC", "MA", "PI", "CE", "RN", "PE", "PB", "SE", "AL", "BA", " " }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(55, 35));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("CADASTRO DO PROFESSOR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 10, 260, 22);

        jButton1_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaM.png"))); // NOI18N
        jButton1_voltar.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton1_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_voltar);
        jButton1_voltar.setBounds(25, 11, 30, 30);

        jLabel1_nome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1_nome.setText("Nome:");
        jLabel1_nome.setPreferredSize(new java.awt.Dimension(66, 35));

        txtLoginProf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLoginProf.setPreferredSize(new java.awt.Dimension(260, 35));

        jLabel2_senha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2_senha.setText("Login:");
        jLabel2_senha.setPreferredSize(new java.awt.Dimension(66, 35));

        jLabel2_senha1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2_senha1.setText("Senha:");
        jLabel2_senha1.setPreferredSize(new java.awt.Dimension(66, 35));

        passSenhaProf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passSenhaProf.setPreferredSize(new java.awt.Dimension(260, 35));

        jButton2_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jButton2_cadastrar.setToolTipText("Cadastrar");
        jButton2_cadastrar.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton2_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_cadastrarActionPerformed(evt);
            }
        });

        jLabel2_senha2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2_senha2.setText("Área:");
        jLabel2_senha2.setPreferredSize(new java.awt.Dimension(66, 35));

        cmbArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Ciências Humanas", "Ciência da Natureza", "Linguagens e Códigos", "Matemática" }));
        cmbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreaActionPerformed(evt);
            }
        });

        txtNomeProf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeProf.setPreferredSize(new java.awt.Dimension(260, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2_senha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2_senha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passSenhaProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLoginProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2_senha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2_senha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(passSenhaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLoginProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 50, 363, 260);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shutterstock_157634834-Converted.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 420);

        setSize(new java.awt.Dimension(505, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_voltarActionPerformed
        
          new TelaProfessor().show();
          dispose();
    }//GEN-LAST:event_jButton1_voltarActionPerformed

    private void jButton2_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_cadastrarActionPerformed
        cadastrarProfessor();
        new TelaProfessor().show();
        dispose();
    }//GEN-LAST:event_jButton2_cadastrarActionPerformed

    private void cmbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbArea;
    private javax.swing.JButton jButton1_voltar;
    private javax.swing.JButton jButton2_cadastrar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_nome;
    private javax.swing.JLabel jLabel2_senha;
    private javax.swing.JLabel jLabel2_senha1;
    private javax.swing.JLabel jLabel2_senha2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passSenhaProf;
    private javax.swing.JTextField txtLoginProf;
    private javax.swing.JTextField txtNomeProf;
    // End of variables declaration//GEN-END:variables

    private String String(char[] password) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    
    private void cadastrarProfessor(){
    
        GetSetProfessor pdt = new GetSetProfessor();

        
      pdt.setNomeProf(txtNomeProf.getText());
      pdt.setLoginProf(txtLoginProf.getText());
      pdt.setSenhaProf(passSenhaProf.getText());
      pdt.setAreaProf((java.lang.String) cmbArea.getSelectedItem());
      
      String SQL = "INSERT INTO professor (nomeProf,loginProf,senhaProf,areaProf)VALUES (?,?,?,?)";
      
        try {
            PreparedStatement pest = (PreparedStatement) con.prepareStatement(SQL);
            
            pest.setString(1,pdt.getNomeProf());
            pest.setString(2,pdt.getLoginProf());
            pest.setString(3,pdt.getSenhaProf());
            pest.setString(4,pdt.getAreaProf());
            
            int rs = pest.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Professor salvo com sucesso!");
            
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"Erro ao inserir !");
             ex.printStackTrace();
        }
}
}
