

package telas;


import java.awt.Toolkit;
import javax.swing.JOptionPane;


  public class ProvaMat01 extends javax.swing.JFrame{      
   // conecta con = new conecta();
    
    
     public ProvaMat01() {
        initComponents();
         //codigo para iniciar com tela maxima
        this.setExtendedState(ProvaMat01.MAXIMIZED_BOTH);
     //   con.conexao();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
   
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton02A = new javax.swing.JRadioButton();
        jRadioButton02B = new javax.swing.JRadioButton();
        jRadioButton02C = new javax.swing.JRadioButton();
        jRadioButton01A = new javax.swing.JRadioButton();
        jRadioButton01B = new javax.swing.JRadioButton();
        jRadioButton01C = new javax.swing.JRadioButton();
        jRadioButton03A = new javax.swing.JRadioButton();
        jRadioButton03B = new javax.swing.JRadioButton();
        jRadioButton03C = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton04A = new javax.swing.JRadioButton();
        jRadioButton04B = new javax.swing.JRadioButton();
        jRadioButton04C = new javax.swing.JRadioButton();
        jRadioButton05B = new javax.swing.JRadioButton();
        jRadioButton05A = new javax.swing.JRadioButton();
        jRadioButton05C = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "AC", "MA", "PI", "CE", "RN", "PE", "PB", "SE", "AL", "BA", " " }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(55, 35));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("1°) Se Maria possui 4 blusas e 5 calças, então o número de combinações entre calça e blusa que ela pode fazer para sair é");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Cada código é composto pelas 6 bandeiras, diferenciando-se apenas pela ordem em que elas aparecem. Quantos códigos diferentes podem ser formados?");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("2°) Vinte times de futebol disputam a Série A do Campeonato Brasileiro, sendo seis deles paulistas. Cada time joga duas vezes contra cada um dos seus adversários. ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("3°) O número de anagramas da palavra ESCOLA, que apresenta as vogais e consoantes alternadas, é");

        buttonGroup2.add(jRadioButton02A);
        jRadioButton02A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton02A.setText("A) menor que 7%.");
        jRadioButton02A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton02AActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton02B);
        jRadioButton02B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton02B.setText("B) maior que 7%, mas menor que 10%.");

        buttonGroup2.add(jRadioButton02C);
        jRadioButton02C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton02C.setText("C) maior que 10%, mas menor que 13%.");

        buttonGroup1.add(jRadioButton01A);
        jRadioButton01A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton01A.setText("A) 10");
        jRadioButton01A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton01AActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton01B);
        jRadioButton01B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton01B.setText("B) 15");
        jRadioButton01B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton01BActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton01C);
        jRadioButton01C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton01C.setText("C) 20");

        buttonGroup3.add(jRadioButton03A);
        jRadioButton03A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton03A.setText("A) 72");
        jRadioButton03A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton03AActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton03B);
        jRadioButton03B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton03B.setText("B) 48");

        buttonGroup3.add(jRadioButton03C);
        jRadioButton03C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton03C.setText("C) 36");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("4°) O número de anagramas da palavra VESTIBULANDO, que apresenta as cinco vogais juntas, é 12!");

        buttonGroup4.add(jRadioButton04A);
        jRadioButton04A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton04A.setText("A) (7!)(5!)");
        jRadioButton04A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton04AActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButton04B);
        jRadioButton04B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton04B.setText("B) (8!)(5!)");

        buttonGroup4.add(jRadioButton04C);
        jRadioButton04C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton04C.setText("C) (10!)(5!)");

        buttonGroup6.add(jRadioButton05B);
        jRadioButton05B.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton05B.setText("B) 20");

        buttonGroup6.add(jRadioButton05A);
        jRadioButton05A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton05A.setText("A) 10");
        jRadioButton05A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton05AActionPerformed(evt);
            }
        });

        buttonGroup6.add(jRadioButton05C);
        jRadioButton05C.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton05C.setText("C) 30");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("5°) Existem 6 bandeiras (de mesmo formato), sendo 3 vermelhas e 3 brancas. Deseja-se transmitir mensagens específicas a partir de códigos formados pelas bandeiras. ");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Terminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jRadioButton03A, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(89, 89, 89))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton03C, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton03B, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jRadioButton04A, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(89, 89, 89))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton04C, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton04B, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton01A, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioButton01C, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRadioButton01B, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jRadioButton02A, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(89, 89, 89))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton02C, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton02B, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9)))
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton05A, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton05B, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton05C, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton01A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton01B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton01C)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton02A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton02B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton02C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton03A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton03B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton03C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton04A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton04B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton04C)
                .addGap(13, 13, 13)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton05A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton05B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton05C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 70, 1250, 610);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("PROVA DE MATEMÁTICA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 10, 260, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/papelProva_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 730);

        setSize(new java.awt.Dimension(1397, 766));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton02AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton02AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton02AActionPerformed

    private void jRadioButton01AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton01AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton01AActionPerformed

    private void jRadioButton03AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton03AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton03AActionPerformed

    private void jRadioButton04AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton04AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton04AActionPerformed

    private void jRadioButton05AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton05AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton05AActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     //Questão 01
     if(jRadioButton01A.isSelected()){
         JOptionPane.showMessageDialog(null,"Você errou a questão 01. Item correto C");
     }if(jRadioButton01B.isSelected()){
         JOptionPane.showMessageDialog(null,"Você errou a questão 01. Item correto C");
     }if(jRadioButton01C.isSelected()){
         JOptionPane.showMessageDialog(null,"Você acertou a questão 01.");
     }
     
     //Questão 02
     if(jRadioButton02A.isSelected()){
         JOptionPane.showMessageDialog(null,"Você errou a questão 02. Item correto B");
     }if(jRadioButton02B.isSelected()){
         JOptionPane.showMessageDialog(null,"Você acertou a questão 02.");
     }if(jRadioButton02C.isSelected()){
         JOptionPane.showMessageDialog(null,"Você errrou questão 02. Item correto B");
     }
     
     //Questão 03
      if(jRadioButton03A.isSelected()){
         JOptionPane.showMessageDialog(null,"Você acertou a questão 03.");
     }if(jRadioButton03B.isSelected()){
         JOptionPane.showMessageDialog(null,"Você errou a questão 03. Item correto A");
     }if(jRadioButton03C.isSelected()){
         JOptionPane.showMessageDialog(null,"Você errrou questão 03. Item correto A");
     }
     
     //Questão 04
      if(jRadioButton04A.isSelected()){
         JOptionPane.showMessageDialog(null,"Você acertou a questão 04.");
     }if(jRadioButton04B.isSelected()){
         JOptionPane.showMessageDialog(null,"Você errou a questão 04. Item correto A");
     }if(jRadioButton04C.isSelected()){
         JOptionPane.showMessageDialog(null,"Você errrou questão 04. Item correto A");
     }
     
     //Questão 05
      if(jRadioButton05A.isSelected()){
         JOptionPane.showMessageDialog(null,"Você errou a questão 05. Item correto B");
     }if(jRadioButton05B.isSelected()){
         JOptionPane.showMessageDialog(null,"Você acertou a questão 05.");
     }if(jRadioButton05C.isSelected()){
         JOptionPane.showMessageDialog(null,"Você errrou questão 05. Item correto B");
     }
     
     new TelaAluno().show();
     dispose();
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton01BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton01BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton01BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProvaMat01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProvaMat01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProvaMat01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProvaMat01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProvaMat01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton01A;
    private javax.swing.JRadioButton jRadioButton01B;
    private javax.swing.JRadioButton jRadioButton01C;
    private javax.swing.JRadioButton jRadioButton02A;
    private javax.swing.JRadioButton jRadioButton02B;
    private javax.swing.JRadioButton jRadioButton02C;
    private javax.swing.JRadioButton jRadioButton03A;
    private javax.swing.JRadioButton jRadioButton03B;
    private javax.swing.JRadioButton jRadioButton03C;
    private javax.swing.JRadioButton jRadioButton04A;
    private javax.swing.JRadioButton jRadioButton04B;
    private javax.swing.JRadioButton jRadioButton04C;
    private javax.swing.JRadioButton jRadioButton05A;
    private javax.swing.JRadioButton jRadioButton05B;
    private javax.swing.JRadioButton jRadioButton05C;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private String String(char[] password) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    
    

}
