/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;


import java.awt.Toolkit;
import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fcovi
 */
public class TelaProfessor extends javax.swing.JFrame {
    
       public TelaProfessor() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));

       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenCad = new javax.swing.JMenu();
        MenCadCli = new javax.swing.JMenuItem();
        MenCadCli1 = new javax.swing.JMenuItem();
        MenCadOs = new javax.swing.JMenuItem();
        MenOpc1 = new javax.swing.JMenu();
        MenAju = new javax.swing.JMenu();
        MenAjuSob = new javax.swing.JMenuItem();
        MenAjuSob1 = new javax.swing.JMenuItem();
        MenAjuSob2 = new javax.swing.JMenuItem();
        MenAju1 = new javax.swing.JMenu();
        MenAjuSob3 = new javax.swing.JMenuItem();
        MenAjuSob4 = new javax.swing.JMenuItem();
        MenAjuSob5 = new javax.swing.JMenuItem();
        MenAjuSob6 = new javax.swing.JMenuItem();
        MenOpc = new javax.swing.JMenu();
        MenOpcSai = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Seja bem vindo Professor!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 20, 240, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shutterstock_157634834-Converted.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 390);

        MenCad.setText("Cadastros");
        MenCad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MenCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenCadCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenCadCli.setText("Aluno");
        MenCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadCliActionPerformed(evt);
            }
        });
        MenCad.add(MenCadCli);

        MenCadCli1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        MenCadCli1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenCadCli1.setText("Professor");
        MenCadCli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadCli1ActionPerformed(evt);
            }
        });
        MenCad.add(MenCadCli1);

        MenCadOs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        MenCadOs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenCadOs.setText("Questões");
        MenCadOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadOsActionPerformed(evt);
            }
        });
        MenCad.add(MenCadOs);

        Menu.add(MenCad);

        MenOpc1.setText("Relatório");
        MenOpc1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MenAju.setText("Alunos");
        MenAju.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MenAjuSob.setText("1º ano");
        MenAjuSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjuSobActionPerformed(evt);
            }
        });
        MenAju.add(MenAjuSob);

        MenAjuSob1.setText("2º ano");
        MenAjuSob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjuSob1ActionPerformed(evt);
            }
        });
        MenAju.add(MenAjuSob1);

        MenAjuSob2.setText("3º ano");
        MenAjuSob2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjuSob2ActionPerformed(evt);
            }
        });
        MenAju.add(MenAjuSob2);

        MenOpc1.add(MenAju);

        MenAju1.setText("Professores");
        MenAju1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MenAjuSob3.setText("Ciências Humanas");
        MenAjuSob3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjuSob3ActionPerformed(evt);
            }
        });
        MenAju1.add(MenAjuSob3);

        MenAjuSob4.setText("Ciências da Natureza");
        MenAjuSob4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjuSob4ActionPerformed(evt);
            }
        });
        MenAju1.add(MenAjuSob4);

        MenAjuSob5.setText("Linguagens e Códigos");
        MenAjuSob5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjuSob5ActionPerformed(evt);
            }
        });
        MenAju1.add(MenAjuSob5);

        MenAjuSob6.setText("Matemática");
        MenAjuSob6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjuSob6ActionPerformed(evt);
            }
        });
        MenAju1.add(MenAjuSob6);

        MenOpc1.add(MenAju1);

        Menu.add(MenOpc1);

        MenOpc.setText("Opções");
        MenOpc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MenOpcSai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenOpcSai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenOpcSai.setText("Sair");
        MenOpcSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpcSaiActionPerformed(evt);
            }
        });
        MenOpc.add(MenOpcSai);

        Menu.add(MenOpc);

        setJMenuBar(Menu);

        setSize(new java.awt.Dimension(514, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadCliActionPerformed
      new Cadastro_aluno().show();
      dispose();
         
    }//GEN-LAST:event_MenCadCliActionPerformed

    private void MenCadOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadOsActionPerformed
        // chamando tela OS
        //  TelaOS os = new TelaOS();
        //os.setVisible(true);
        //desktop.add(os);
    }//GEN-LAST:event_MenCadOsActionPerformed

    private void MenAjuSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjuSobActionPerformed
        // Chamando a tela sobre
        //  TelaSobre sobre = new TelaSobre();
        //sobre.setVisible(true);
    }//GEN-LAST:event_MenAjuSobActionPerformed

    private void MenAjuSob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjuSob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenAjuSob1ActionPerformed

    private void MenAjuSob2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjuSob2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenAjuSob2ActionPerformed

    private void MenAjuSob3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjuSob3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenAjuSob3ActionPerformed

    private void MenAjuSob4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjuSob4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenAjuSob4ActionPerformed

    private void MenAjuSob5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjuSob5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenAjuSob5ActionPerformed

    private void MenAjuSob6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjuSob6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenAjuSob6ActionPerformed

    private void MenOpcSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpcSaiActionPerformed
        // Exibe uma caixa de diálogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MenOpcSaiActionPerformed

    private void MenCadCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadCli1ActionPerformed
        new Cadastro_Professor().show();
        dispose();

    }//GEN-LAST:event_MenCadCli1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenAju;
    private javax.swing.JMenu MenAju1;
    private javax.swing.JMenuItem MenAjuSob;
    private javax.swing.JMenuItem MenAjuSob1;
    private javax.swing.JMenuItem MenAjuSob2;
    private javax.swing.JMenuItem MenAjuSob3;
    private javax.swing.JMenuItem MenAjuSob4;
    private javax.swing.JMenuItem MenAjuSob5;
    private javax.swing.JMenuItem MenAjuSob6;
    private javax.swing.JMenu MenCad;
    private javax.swing.JMenuItem MenCadCli;
    private javax.swing.JMenuItem MenCadCli1;
    private javax.swing.JMenuItem MenCadOs;
    private javax.swing.JMenu MenOpc;
    private javax.swing.JMenu MenOpc1;
    private javax.swing.JMenuItem MenOpcSai;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
